<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.56</Version>
      
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild> <Authors>Almacendora del pacífico - Group</Authors>
    <Company>Almacendora del pacífico s.a.</Company>
    <Description>Core Domain layer for Alpac ERP system.</Description>
  </PropertyGroup>

</Project>
